### ISSUE TITLE
openelec 5.0.5 odroidc no more remote

### ISSUE THREAD

**Issue by erdoukki** [zalaare/OpenELEC-Odroid#10]
openelec 5.0.5 odroidc has no more remote

**Comment by zalaare** [comment]
Yes.  I noticed this as well.  I'll look into fixing it for 5.0.6.  My guess its the switch to LIRC meson-ir driver broke the native amlogic remote setup.  I'll look at what mdrjr is doing in Ubuntu and attempt to replicate it.

**Comment by zalaare** [comment]
Fixed in 5.0.6
