### ISSUE TITLE
How can I build the image on my own env ?

### ISSUE THREAD

**Issue by luoyi** [zalaare/OpenELEC-Odroid#11]
Hi, could you kind enough to provide a file tell us that how can I build this image on my own box ?

**Comment by MichaelSp** [comment]
This is what I did:
Install build [dependencies](http://wiki.openelec.tv/index.php/Compile_from_source)
```
git clone https://github.com/zalaare/OpenELEC-Odroid.git
cd OpenELEC-Odroid
PROJECT=Odroid make release
```

still waiting for it to finish.
