### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by henningvs** [zalaare/OpenELEC-Odroid#14]
When trying to build the project with the following:
``` make PROJECT=Odroid DEVICE=U2 image```

This error does appear. Seems like an DNS resolving error?
```
--2016-01-06 20:32:16--  http://freeweb.mine.nu/zalaare/linux-0.0invalid.tar.xz
Resolving freeweb.mine.nu (freeweb.mine.nu)... 178.32.220.211
Connecting to freeweb.mine.nu (freeweb.mine.nu)|178.32.220.211|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-01-06 20:32:16 ERROR 404: Not Found.

--2016-01-06 20:32:16--  http://sources.openelec.tv/mirror/linux/linux-0.0invalid.tar.xz
Resolving sources.openelec.tv (sources.openelec.tv)... 82.220.2.33
Connecting to sources.openelec.tv (sources.openelec.tv)|82.220.2.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-01-06 20:32:16 ERROR 404: Not Found.
```

**Comment by zalaare** [comment]
It appears that the PKG_VERSION for the DEVICE=U2 is not resolving to a name.  What commit are you on?  Please verify you are in branch odroid-6.0 and you are up-to-date.  I'm checking into this too.

**Comment by zalaare** [comment]
```
          GET      linux
converted 'http://freeweb.mine.nu/zalaare/linux-3.8.13+1130f87.tar.xz' (ANSI_X3.4-1968) -> 'http://freeweb.mine.nu/zalaare/linux-3.8.13+1130f87.tar.xz' (UTF-8)
--2016-01-06 20:43:26--  http://freeweb.mine.nu/zalaare/linux-3.8.13+1130f87.tar.xz
Resolving freeweb.mine.nu (freeweb.mine.nu)... 178.32.220.211
Connecting to freeweb.mine.nu (freeweb.mine.nu)|178.32.220.211|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 75005720 (72M) [application/x-xz]
Saving to: 'sources/linux/linux-3.8.13+1130f87.tar.xz'

sources/linux/linux-3.8.13+1130f87.tar.xz             11%[============>            
```

This seems to be okay for me when up to date and in branch odroid-6.0

**Comment by henningvs** [comment]
I tried it with the latest release. But I will pull the newest version from github an try again.

**Comment by zalaare** [comment]
Please let me know if you were successful.  I was able to complete a fresh U2 build last night with fresh downloading of sources wo issue.

**Comment by henningvs** [comment]
Sorry for my late response. Just wanted to let you know that I had success with building the newest version. I guess this was related to a problem with resolving ```freeweb.mine.nu```. But as this problem doesn't exist anymore the problem seems to be solved.
Maybe you could also include those files in the repo to prevent such failures in the future?
