### ISSUE TITLE
Merge problem

### ISSUE THREAD

**Issue by Gotrek77** [zalaare/OpenELEC-Odroid#15]
Hi,
there was a merge problem in:
OpenELEC-Odroid/projects/Odroid/packages/libdrm/package.mk
on branch odroid-7.

**Comment by zalaare** [comment]
Current branch is something I'm still working on.  Expect problems.

**Comment by Gotrek77** [comment]
Uhm... I know this but I think that can be useful to indicate you if there was a stupid problem that was happen during merge... I fix it in local:
diff --git a/projects/Odroid/packages/libdrm/package.mk b/projects/Odroid/packages/libdrm/package.mk
index 3c32000..adae7e9 100644
--- a/projects/Odroid/packages/libdrm/package.mk
+++ b/projects/Odroid/packages/libdrm/package.mk
@@ -1,10 +1,6 @@
 ################################################################################
 #      This file is part of OpenELEC - http://www.openelec.tv
-<<<<<<< HEAD
 #      Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
-=======
-#      Copyright (C) 2009-2014 Stephan Raue (stephan@openelec.tv)
->>>>>>> f489a80a4532960b0e1434e3169844647218710a
 #
 #  OpenELEC is free software: you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
