### ISSUE TITLE
Ethernet Connection Issue XU3 Openelrc 

### ISSUE THREAD

**Issue by yamsu** [zalaare/OpenELEC-Odroid#19]

**Comment by yamsu** [comment]
Running openelec 6.0.0.1
Ethernet connection doesn't work. XBMC is unable to find any network.
I have connected the XU3 to a router via CAT5e. This works fine with ubuntu and android images.
Unable yo ssh so I do not have any debug information. I can say that the ethernet port light on the router is on when the connection is device is turned on. System run fine otherwise, but no network. Any ideas?

**Comment by zalaare** [comment]
Get a USB UART and see what is happening.  Without a UART you are sailing blind without a sail. <-Hyperbole

http://www.hardkernel.com/main/products/prdt_info.php?g_code=G134111883934

**Comment by yamsu** [comment]
Hi final solution was to use the openelec image provided on the odroid forum, 6.95.x
This is available at the following link http://forum.odroid.com/viewtopic.php?f=79&t=5915
