### ISSUE TITLE
Odroid C2

### ISSUE THREAD

**Issue by lrusak** [zalaare/OpenELEC-Odroid#20]
Just dropping you a line to see if you have OpenELEC working on the Odroid-C2.

I am able to compile OpenELEC for the Odroid-C2 and it runs, however kodi segfaults and I cannot figure out why.

see my tree here, https://github.com/lrusak/openelec.tv/tree/aarch64-odroid-c2

**Comment by zalaare** [comment]
I don't.  I've been fighting with U-Boot (again) and attempting to port the DEVICE tree to the recently added .openelec (vendor) tree.

**Comment by zalaare** [comment]
--- Provided fip_create
odroid@fortress ..ch64-6.95.0/u-boot-2015.01+beda694/fip (git)-[odroid-7.0] % ./fip_create
ERROR: Missing FIP filename
Usage: fip_create [options] FIP_FILENAME

        This tool is used to create a Firmware Image Package.

Options:
        --help: Print this help message and exit
        --dump: Print contents of FIP

        Components that can be added/updated:
        --bl2 FILENAME          Trusted Boot Firmware BL2
        --bl30 FILENAME         SCP Firmware BL3-0
        --bl301 FILENAME                SCP Firmware BL3-0-1
        --bl31 FILENAME         EL3 Runtime Firmware BL3-1
        --bl32 FILENAME         Secure Payload BL3-2 (Trusted OS)
        --bl33 FILENAME         Non-Trusted Firmware BL3-3

--- Vs. Official fip_create
odroid@fortress ..ch64-6.95.0/u-boot-2015.01+beda694/fip (git)-[odroid-7.0] % fip_create
ERROR: Missing FIP filename
Usage: fip_create [options] FIP_FILENAME

        This tool is used to create a Firmware Image Package.

Options:
        --help: Print this help message and exit
        --dump: Print contents of FIP

        Components that can be added/updated:
        --scp-fwu-cfg FILENAME          SCP Firmware Updater Configuration FWU SCP_BL2U
        --ap-fwu-cfg FILENAME           AP Firmware Updater Configuration BL2U
        --fwu FILENAME          Firmware Updater NS_BL2U
        --fwu-cert FILENAME             Non-Trusted Firmware Updater certificate
        --tb-fw FILENAME                Trusted Boot Firmware BL2
        --scp-fw FILENAME               SCP Firmware SCP_BL2
        --soc-fw FILENAME               EL3 Runtime Firmware BL31
        --tos-fw FILENAME               Secure Payload BL32 (Trusted OS)
        --nt-fw FILENAME                Non-Trusted Firmware BL33
        --rot-cert FILENAME             Root Of Trust key certificate
        --trusted-key-cert FILENAME             Trusted key certificate
        --scp-fw-key-cert FILENAME              SCP Firmware key certificate
        --soc-fw-key-cert FILENAME              SoC Firmware key certificate
        --tos-fw-key-cert FILENAME              Trusted OS Firmware key certificate
        --nt-fw-key-cert FILENAME               Non-Trusted Firmware key certificate
        --tb-fw-cert FILENAME           Trusted Boot Firmware BL2 certificate
        --scp-fw-cert FILENAME          SCP Firmware content certificate
        --soc-fw-cert FILENAME          SoC Firmware content certificate
        --tos-fw-cert FILENAME          Trusted OS Firmware content certificate
        --nt-fw-cert FILENAME           Non-Trusted Firmware content certificate

**Comment by Kivutar** [comment]
Is the FIP step really needed?

If you comment it in the makefile, the u-boot.bin will still build. (But I'm not sure if it will be good)

**Comment by lrusak** [comment]
hmm, I don't have a problem building u-boot, but it doesn't seem to want to boot the kernel, it just hangs.

Using the hardkernel supplied u-boot works fine.

**Comment by zalaare** [comment]
Yes, FIP is really needed.  I talked to mdrjr and he verified the fip_create included with the HardKernel u-boot source is different from the reference fip_create (which is why I can't get the reference fip_create to work).  I've had to modify my docker container to simply include libc for both architectures for now.

Now I am past U-Boot and digging into the Linux kernel itself.  My problem is likely the custom init needs updating to support the C2.

Did you re-implement the INITCPIO built-into the kernel support that OE uses with success?  I could not get it to work with any of my Odroid's and quickly split the initrd into a seperate file /INITRD and re-wrote the init script to handle that ontop of the /KERNEL and /SYSTEM files.

**Comment by zalaare** [comment]
I just opened a PR to fix some issues with using the new $HOME/.openelec vendor directory for holding a custom project tree.  https://github.com/OpenELEC/OpenELEC.tv/pull/4818.  This may or may not help you.  I noted that many of the changes you made for the Odroid_C2 still didn't address the problems that may occur if someone wanted to (easily) add another (Odroid_C1 for example).

**Comment by lrusak** [comment]
@zalaare no need for an INITRD. see [here](https://github.com/lrusak/OpenELEC.tv/blob/ee6eadd087265996818ca25a2fc0483c881ea912/projects/Odroid_C2/bootloader/boot.ini#L153-L156)

**Comment by Kivutar** [comment]
@zalaare In Lakka, i'm not using any separate initrd. Let take a look at these odroid projects: https://github.com/libretro/Lakka/tree/lakka/projects

**Comment by zalaare** [comment]
@lrusak What I'm having trouble wrapping my head around is that you don't use INITRD and you don't include the rootfs in the KERNEL [see here](https://github.com/lrusak/OpenELEC.tv/blob/ee6eadd087265996818ca25a2fc0483c881ea912/projects/Odroid_C2/linux/linux.aarch64.conf#L112) where is /init? (initramfs, uInitrd, etc.)

@Kivutar Codesnake did up that device folder stuff way back and it was great for me as I was able to keep dropping Odroid "devices" into my "Odroid" project with only a some minor changes.  It made maintaining the various packages easier for me.  But with the recent $HOME/.openelec support popping into master, I don't see any reason not to port it all over to that.

**Comment by Kivutar** [comment]
@zalaare Looks like @lrusak just let openelec build the initrd and bake it in the kernel, like it's done on other OE project. This line https://github.com/lrusak/OpenELEC.tv/blob/ee6eadd087265996818ca25a2fc0483c881ea912/projects/Odroid_C2/linux/linux.aarch64.conf#L112 have to stay empty, and will be filled during the build process, before the kernel is compiled.

**Comment by zalaare** [comment]
@Kivutar Yes I see where this is happening [here](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/linux/package.mk#L71-L73). I remember when I first did the Odroid-U2, this would not work no matter what I tried.  I ended up giving up and adding a separate initrd from then on.  I'll have to try this all again since it has been awhile since then. Thanks!

**Comment by hcbraun** [comment]
I build with newer versions of u-boot / kernel from hardkernel. It starts Kodi. But so far i can't get video playback working
https://github.com/hcbraun/OpenELEC-Odroid/commits/odroid-7.0-c2
