### ISSUE TITLE
mkimage corrupts first partition and or fused data

### ISSUE THREAD

**Issue by zalaare** [zalaare/OpenELEC-Odroid#22]
Hopefully someone more knowledgeable than I can take a look at this with me.

I created my own mkimage-odroid script because I couldn't get a reliable image out of mkimage when I first starting building OpenELEC for Odroid images.

I have again reverted to mainline's mkimage now that the infrastructure exists to do [custom fusing](https://github.com/zalaare/OpenELEC-Odroid/blob/odroid-7.0/scripts/mkimage#L202-L204).  I've an example [here](https://github.com/zalaare/OpenELEC-Odroid/blob/odroid-7.0/.openelec/projects/Odroid-U2/bootloader/u-boot-fuse) for the Odroid-U2 project.

**Comment by Kivutar** [comment]
Did you check the STORAGE_PART_START? Corruption happens when the dd intervals overlap.

**Comment by zalaare** [comment]
Honestly I didn't look at STORAGE_PART_START because if there is a dd overlap there, then it affects every OpenELEC project (this is the mainline mkimage script).  I think the overlap is occurring between sector 2048 and 2423 (based on my math).

The trustzone for Odroid-U2 starts at sector [2111](https://github.com/zalaare/OpenELEC-Odroid/blob/odroid-7.0/.openelec/projects/Odroid-U2/bootloader/u-boot-fuse#L7) and it writes 312 blocks so with the blocksize still at 512 I get the tzsw ending at sector 2423 || 159744 bytes later.  This would then SEEM like it would be easily fixed by starting the fat partition at sector 3072 (1.5MB in).  Which is currently what I am testing.

**Comment by zalaare** [comment]
However, even when using 3072 as the first partition start sector, I am not able to get the partition to mount during rootfs /init.  I'm currently trying to figure out if something is missing in my Linux kernel that is causing this as I have to `assume` that this isn't corruption caused by overlapping dd blocks between U-Boot and Partition 1.

**Comment by Kivutar** [comment]
What result do you get if you just skip the u-boot package in OpenELEC, and use the u-boot and sd_fuse provided by hardkernel? You get the same overlaps?

**Comment by zalaare** [comment]
This isn't an overlap problem at all.  I've verified and re-verified all blocks and accounted for them.  I'm sure this is simple a typo or misconfiguration in my linux .config file.  I'm going through it again.  Sometimes a fresh day is all that is needed to find a problem.
