### ISSUE TITLE
.openelec won't build 

### ISSUE THREAD

**Issue by stormrev** [zalaare/OpenELEC-Odroid#24]
Hi zalaare, I've copied from .openelec/projects/Odroid-C2 to projects dir 
but openelec fails to build the linux kernel using cmdline:

 PROJECT=Odroid-C2 ARCH=aarch64 make 

Did i miss something?

thank you

**Comment by zalaare** [comment]
Why would you expect it to build?  Please expect that unreleased development branches could potentially not build.
