### ISSUE TITLE
new kernel for odroid u2 does not fully boot

### ISSUE THREAD

**Issue by nfstry** [zalaare/OpenELEC-Odroid#8]
just cloned the tree (branch 6.0) and built. first issue was that boot.ini not recognized by uboot:
reading boot.ini
2699 bytes read in 21 ms (125 KiB/s)
Loading boot.ini from FAT
Find boot.ini file. But This file is not ODROID config file!
Odroid #

then i applied the set of commands from th boot.ini from sources into the console and run boot. kernel hangs after 1 sec

U-Boot 2015.04+19e5118 (Mar 25 2015 - 19:01:58)

CPU:    Exynos4412@1000MHz
Model: Odroid based on Exynos4412
DRAM:  2 GiB
Board PMIC init
MMC:   SAMSUNG SDHCI: 0, EXYNOS DWMMC: 1
Net:   No ethernet found.
Hit any key to stop autoboot:  0
reading KERNEL
2452720 bytes read in 232 ms (10.1 MiB/s)
reading INITRD
3379264 bytes read in 327 ms (9.9 MiB/s)
reading exynos4412-odroidu3.dtb
54296 bytes read in 24 ms (2.2 MiB/s)
Kernel image @ 0x40080000 [ 0x000000 - 0x256cf0 ]
## Loading init Ramdisk from Legacy Image at 42000000 ...
   Image Name:   RootFS [Odroid]
   Image Type:   ARM Linux RAMDisk Image (uncompressed)
   Data Size:    3379200 Bytes = 3.2 MiB
   Load Address: 00000000
   Entry Point:  00000000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 44000000
   Booting using the fdt blob at 0x44000000
   Using Device Tree in place at 44000000, end 44010417

Starting kernel ...

Uncompressing Linux... done, booting the kernel.
[    0.000000] Booting Linux on physical CPU 0xa00
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.19.2+0f25c54 (nfstry@mymachine) (gcc version 4.9.2 (GCC) ) #1 SMP PREEMPT Wed Mar 25 19:15:10 CET 2015
[    0.000000] CPU: ARMv7 Processor [413fc090] revision 0 (ARMv7), cr=10c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] Machine model: Hardkernel ODROID-U3 board based on Exynos4412
[    0.000000] Reserved memory: created CMA memory pool at 0x77000000, size 16 MiB
[    0.000000] Reserved memory: initialized node region@77000000, compatible id shared-dma-pool
[    0.000000] Reserved memory: created CMA memory pool at 0x78000000, size 16 MiB
[    0.000000] Reserved memory: initialized node region@78000000, compatible id shared-dma-pool
[    0.000000] cma: Reserved 128 MiB at 0xb7c00000
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] Running under secure firmware.
[    0.000000] PERCPU: Embedded 9 pages/cpu @ee79b000 s7808 r8192 d20864 u36864
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 522512
[    0.000000] Kernel command line: console=ttySAC1,115200n8 boot=LABEL=System disk=LABEL=Storage ro
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 1904504K/2096128K available (4705K kernel code, 184K rwdata, 1488K rodata, 228K init, 228K bss, 60552K reserved, 131072K cma-reserved, 1154048K highmem)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
[    0.000000]     vmalloc : 0xf0000000 - 0xff000000   ( 240 MB)
[    0.000000]     lowmem  : 0xc0000000 - 0xef800000   ( 760 MB)
[    0.000000]     pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
[    0.000000]     modules : 0xbf000000 - 0xbfe00000   (  14 MB)
[    0.000000]       .text : 0xc0008000 - 0xc0614788   (6194 kB)
[    0.000000]       .init : 0xc0615000 - 0xc064e000   ( 228 kB)
[    0.000000]       .data : 0xc064e000 - 0xc067c000   ( 184 kB)
[    0.000000]        .bss : 0xc067c000 - 0xc06b53b8   ( 229 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000000] L2C: platform modifies aux control register: 0x02070000 -> 0x3e470001
[    0.000000] L2C: platform provided aux values permit register corruption.
[    0.000000] L2C: DT/platform modifies aux control register: 0x02070000 -> 0x3e470001
[    0.000000] L2C-310 enabling early BRESP for Cortex-A9
[    0.000000] L2C-310: enabling full line of zeros but not enabled in Cortex-A9
[    0.000000] L2C-310 ID prefetch enabled, offset 1 lines
[    0.000000] L2C-310 dynamic clock gating enabled, standby mode enabled
[    0.000000] L2C-310 cache controller enabled, 16 ways, 1024 kB
[    0.000000] L2C-310: CACHE_ID 0x4100c4c8, AUX_CTRL 0x7e470001
[    0.000000] Exynos4x12 clocks: sclk_apll = 1000000000, sclk_mpll = 800000000
[    0.000000]  sclk_epll = 96000000, sclk_vpll = 350000000, arm_clk = 1000000000
[    0.000000] Switching to timer-based delay loop, resolution 41ns
[    0.000005] sched_clock: 32 bits at 24MHz, resolution 41ns, wraps every 178956969942ns
[    0.000192] Console: colour dummy device 80x30
[    0.000212] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=120000)
[    0.000223] pid_max: default: 32768 minimum: 301
[    0.000315] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000325] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000801] Initializing cgroup subsys devices
[    0.000825] CPU: Testing write buffer coherency: ok
[    0.001076] CPU0: thread -1, cpu 0, socket 10, mpidr 80000a00
[    0.001431] Setting up static identity map for 0x40478c88 - 0x40478ce0
[    0.030467] CPU1: thread -1, cpu 1, socket 10, mpidr 80000a01
[    0.040456] CPU2: thread -1, cpu 2, socket 10, mpidr 80000a02
[    0.050444] CPU3: thread -1, cpu 3, socket 10, mpidr 80000a03
[    0.050485] Brought up 4 CPUs
[    0.050502] SMP: Total of 4 processors activated (192.00 BogoMIPS).
[    0.050507] CPU: All CPU(s) started in SVC mode.
[    0.050950] devtmpfs: initialized
[    0.051754] VFP support v0.3: implementor 41 architecture 3 part 30 variant 9 rev 4
[    0.058112] pinctrl core: initialized pinctrl subsystem
[    0.069790] NET: Registered protocol family 16
[    0.071481] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.085480] cpuidle: using governor ladder
[    0.100476] cpuidle: using governor menu
[    0.105904] exynos-audss-clk 3810000.clock-controller: setup completed
[    0.121966] hw-breakpoint: found 5 (+1 reserved) breakpoint and 1 watchpoint registers.
[    0.121978] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.122479] lcd0-power-domain has as child subdomain: tv-power-domain.
[    0.129637] SCSI subsystem initialized
[    0.129907] usbcore: registered new interface driver usbfs
[    0.129967] usbcore: registered new interface driver hub
[    0.130049] usbcore: registered new device driver usb
[    0.130770] s3c-i2c 13860000.i2c: slave address 0x10
[    0.130782] s3c-i2c 13860000.i2c: bus frequency set to 390 KHz
[    0.158844] s3c-i2c 13860000.i2c: i2c-0: S3C I2C adapter
[    0.159050] s3c-i2c 13870000.i2c: slave address 0x10
[    0.159062] s3c-i2c 13870000.i2c: bus frequency set to 390 KHz
[    0.159422] s3c-i2c 13870000.i2c: i2c-1: S3C I2C adapter
[    0.159549] s3c-i2c 13880000.i2c: slave address 0x00
[    0.159560] s3c-i2c 13880000.i2c: bus frequency set to 97 KHz
[    0.159702] s3c-i2c 13880000.i2c: i2c-2: S3C I2C adapter
[    0.159788] s3c-i2c 138e0000.i2c: slave address 0x00
[    0.159799] s3c-i2c 138e0000.i2c: bus frequency set to 97 KHz
[    0.160148] s3c-i2c 138e0000.i2c: i2c-8: S3C I2C adapter
[    0.160319] Linux video capture interface: v2.00
[    0.160759] Advanced Linux Sound Architecture Driver Initialized.
[    0.161347] Switched to clocksource mct-frc
[    0.170108] NET: Registered protocol family 2
[    0.170627] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.170691] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.170789] TCP: Hash tables configured (established 8192 bind 8192)
[    0.170842] TCP: reno registered
[    0.170855] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.170893] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.171053] NET: Registered protocol family 1
[    0.171462] hw perfevents: enabled with armv7_cortex_a9 PMU driver, 7 counters available
[    0.172644] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.172799] audit: initializing netlink subsys (disabled)
[    0.172836] audit: type=2000 audit(0.170:1): initialized
[    0.180963] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.181871] bounce: pool size: 64 pages
[    0.182052] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 253)
[    0.182069] io scheduler noop registered
[    0.182102] io scheduler cfq registered (default)
[    0.182513] exynos-mipi-video-phy 10020710.video-phy: can't request region for resource [mem 0x10020710-0x10020717]
[    0.182530] exynos-mipi-video-phy: probe of 10020710.video-phy failed with error -16
[    0.187125] dma-pl330 12680000.pdma: Loaded driver for PL330 DMAC-141330
[    0.187140] dma-pl330 12680000.pdma:         DBUFF-32x4bytes Num_Chans-8 Num_Peri-32 Num_Events-32
[    0.189710] dma-pl330 12690000.pdma: Loaded driver for PL330 DMAC-141330
[    0.189724] dma-pl330 12690000.pdma:         DBUFF-32x4bytes Num_Chans-8 Num_Peri-32 Num_Events-32
[    0.190549] dma-pl330 12850000.mdma: Loaded driver for PL330 DMAC-141330
[    0.190561] dma-pl330 12850000.mdma:         DBUFF-64x8bytes Num_Chans-8 Num_Peri-1 Num_Events-32
[    0.242416] 13800000.serial: ttySAC0 at MMIO 0x13800000 (irq = 70, base_baud = 0) is a S3C6400/10
[    0.242775] 13810000.serial: ttySAC1 at MMIO 0x13810000 (irq = 71, base_baud = 0) is a S3C6400/10
[    0.971647] console [ttySAC1] enabled
[    0.975864] [drm] Initialized drm 1.1.0 20060810
[    0.981371] 12d00000.hdmi supply hdmi-en not found, using dummy regulator
[    0.987868] s5p-g2d 10800000.g2d: The exynos g2d(ver 4.1) successfully probed
[    0.994595] exynos-drm exynos-drm: bound 12c10000.mixer (ops mixer_component_ops)
[    1.001413] exynos-drm exynos-drm: bound 12d00000.hdmi (ops hdmi_component_ops)
[    1.008506] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    1.015099] [drm] No driver support for vblank timestamp query.

**Comment by zalaare** [comment]
I know.  I highly recommend you stay out of odroid-6.0 as its a playground for me at the moment.

**Comment by zalaare** [comment]
I'm using odroid-6.0 branch currently to try to get mainline Linux, and mainline U-Boot working with the U3.  Even without all the features.  If I can get it to boot, then its less work later.
